### ISSUE TITLE
Common config: enhancement to reactor_config prebuild plugin

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#687]
The `reactor_config` plugin could take additional parameters and use them to update the config object it stores. For this to be useful it should be possible not to specify a config_path parameter.

This could be used to store configuration required by multiple plugins, for example Koji information (URLs, certificates) etc.

The benefit of this is that configuration does not have to be set for each and every plugin requiring a particular configuration value.

Example:
```
{
  "name": "reactor_config",
  "args": {
    "config_path": "/var/run/secrets/config.yaml",
    "integrations": {
      "koji": {
        "kojihub": "...",
        "kojiroot": "...",
        "target": "...",
        "koji_proxy_user": "...",
        "koji_ssl_certs_dir": "...",
        ...
      }
    }
  },
  {
    "name": "koji"
  }
}
```

Resulting object returned by `get_config()` would be something like:

```
{
  "version: 1,
  "clusters": {
    ...
  },
  "integrations": {
    "koji": {
      "kojihub": "...",
      "kojiroot": "...",
      "target": "...",
      "koji_proxy_user": "...",
      "koji_ssl_certs_dir": "...",
      ...
    }
  }
}
```

**Comment by twaugh** [comment]
This will require a new plugin "arrangement version".

**Comment by twaugh** [comment]
Even better would be to use 3.6.1's ConfigMap support for BuildConfigs, i.e.
```
  strategy:
    customStrategy:
      env:
        - name: ...
          valueFrom:
            - configMapKeyRef:
                name: ...
                key: ...
                optional: true/false
```

and have `get_config()` parse a base64-encoded environment variable populated that way.
